### ISSUE TITLE
Códigos de confirmación v2.4

### ISSUE THREAD

**Issue by elmendacorp** [2beDigital/spree_redsys#6]
Desde aproximadamente noviembre de 2017 no se reciben los códigos de estado del pago, quedándose este en pendiente, pese a que en la plataforma de pago salen aceptados. He revisado el manual de la api de redsys, pero está anticuado.
Se sabe si con la versión 3 se soluciona esto, ya que los pedidos se quedan sin pasar a estado completado debido a este problema.

**Comment by NoelDiazMesa** [comment]
De momento no tenemos problemas con la versión 2.4, de todas formas nos hemos pasado a Solidus por lo que no estamos mejorando estas gemas. Disculpa las molestias

**Comment by picazoH** [comment]
@elmendacorp Por lo que comentas parece un problema de notificaciones desde el banco, deberías ver en la consola del banco la razón, es probable que sea por un tema de certificados (diría que redsys no los acepta todos)... Tienes la opción en el backend de añadir una url de notificaciones que vaya sin https.  Saludos
